version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./backend:/backend
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    tty: true
